export const vendorCustomerOrder = {
  VendorCustomerOrderGet: {
    data: [
      {
        id: 1,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 300,
        description: 'none',
        status_id: 1,
        created_at: '2022-10-14T11:52:08.262Z',
        updated_at: '2022-10-14T11:52:08.262Z',
        order_id: 1,
        vehicle_id: 1,
        vehicle_name: 'Truck',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 1,
        order_items: ['Cloth Waste'],
        order_images: ['image1']
      },
      {
        id: 2,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 1500,
        description: 'none',
        status_id: 1,
        created_at: '2022-10-14T11:52:25.366Z',
        updated_at: '2022-10-14T11:52:25.366Z',
        order_id: 2,
        vehicle_id: 1,
        vehicle_name: 'Truck',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 2,
        order_items: ['e waste'],
        order_images: ['image1']
      },
      {
        id: 7,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 300,
        description: 'none',
        status_id: 1,
        created_at: '2022-10-14T11:52:08.262Z',
        updated_at: '2022-10-14T11:52:08.262Z',
        order_id: 7,
        vehicle_id: 1,
        vehicle_name: 'Truck',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 1,
        order_items: ['Cloth Waste'],
        order_images: ['image1']
      },
      {
        id: 8,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 300,
        description: 'none',
        status_id: 1,
        created_at: '2022-10-14T11:52:08.262Z',
        updated_at: '2022-10-14T11:52:08.262Z',
        order_id: 8,
        vehicle_id: 1,
        vehicle_name: 'Truck',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 1,
        order_items: ['Cloth Waste'],
        order_images: ['image1']
      },
      {
        id: 9,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 300,
        description: 'none',
        status_id: 1,
        created_at: '2022-10-14T11:52:08.262Z',
        updated_at: '2022-10-14T11:52:08.262Z',
        order_id: 9,
        vehicle_id: 1,
        vehicle_name: 'Truck',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 1,
        order_items: ['Cloth Waste'],
        order_images: ['image1']
      }
    ],
    status: 200
  }
};

export const vendorCustomerOrderScheduled = {
  VendorCustomerOrderGet: {
    data: [
      {
        id: 3,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 1700,
        description: 'none',
        status_id: 2,
        created_at: '2022-10-14T11:52:56.410Z',
        updated_at: '2022-10-14T11:52:56.410Z',
        order_id: 3,
        vehicle_id: 2,
        vehicle_name: 'Tempo',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 3,
        order_items: ['Cloth Waste'],
        order_images: ['image1']
      },
      {
        id: 4,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 1400,
        description: 'none',
        status_id: 2,
        created_at: '2022-10-14T11:53:40.426Z',
        updated_at: '2022-10-14T11:53:40.426Z',
        order_id: 4,
        vehicle_id: 3,
        vehicle_name: 'Tata ace',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 4,
        order_items: ['e waste', 'plastic'],
        order_images: ['image1', 'image2']
      }
    ],
    status: 200
  }
};


export const vendorCustomerOrderCompleted = {
  VendorCustomerOrderGet: {
    data: [
      {
        id: 3,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 1700,
        description: 'none',
        status_id: 3,
        created_at: '2022-10-14T11:52:56.410Z',
        updated_at: '2022-10-14T11:52:56.410Z',
        order_id: 3,
        vehicle_id: 2,
        vehicle_name: 'Tempo',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 3,
        order_items: ['Cloth Waste'],
        order_images: ['image1']
      },
      {
        id: 4,
        order_type_id: 1,
        order_type: 'Customer Order',
        user_type_id: 3,
        user_type: 'Industry',
        orderer_id: 2,
        customer_id: 2,
        registered_mobile_number: '918270129129',
        first_name: 'surya',
        last_name: 'd',
        email: 'lohi.s@gmail.com',
        quantity_kg: 1400,
        description: 'none',
        status_id: 3,
        created_at: '2022-10-14T11:53:40.426Z',
        updated_at: '2022-10-14T11:53:40.426Z',
        order_id: 4,
        vehicle_id: 3,
        vehicle_name: 'Tata ace',
        pickup_time: '2022-09-13T05:29:10.414Z',
        slot: 'evening',
        address:
          'New No: 103,4th cross street,Ram Nagar,tirunelveli,Tamil Nadu',
        city: 'tirunelveli',
        pincode: '600041',
        order_mobile_number: '9876534893',
        map_location: 'map_url',
        address_order_id: 4,
        order_items: ['e waste', 'plastic'],
        order_images: ['image1', 'image2']
      }
    ],
    status: 200
  }
};

